title: Edwin Nellickal # your name (or website title) here
logo: "/images/mugshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/harb7nger/">LinkedIn</a> 
theme: jekyll-theme-minimal
